### PR TITLE
New feature

### PR DESCRIPTION
**Pull request by jakeyboi1**
This optimizes code
Adds Card Collecting which will spawn cards at set locations in config and each player can collect the card once per restart, and will be given 1 of the set card item
Version Bump

### CODE REVIEW

**Comment by mNm-server** [comment]
If you want to further optimize it, remove the antiquated Citizen.'s and swap the GDBC to vector math.

**Comment by jakeyboi1** [comment]
> If you want to further optimize it, remove the antiquated Citizen.'s and swap the GDBC to vector math.

Not sure what you mean by  antiquated Citizen.'s. Also just not a fan of vector math, confuses me so I just rather use GDBC even though I know its a little slower

**Comment by AndrewR3K** [comment]
No need to do Citizen. On things like Wait, CreateThread, etc

for example Citizen.Wait(100) could just be Wait(100)

**Comment by mNm-server** [comment]
Things like "Citizen.Wait" can just be "Wait" and "Citizen.CreateThread" can become "CreateThread". Totally up to you, it's just a lua bennifit and easier because you don't have to break out coords to x, y, z. You can just do two variables that = vector3s. Less variables too since you can just use things that return vector3s as well.

**Comment by jakeyboi1** [comment]
Ahhh yea makes sense. Removed the citizen's for just normal Waits

**Review by AndrewR3K — APPROVED** [review]

**Pull request merged**
